### ISSUE TITLE
genome = '../deepenhancer/temp/sequences.hkl'

### ISSUE THREAD

**Issue by guoyanb** [minxueric/ismb2017_lstm#1]
Hello, the work is very amazing, and i am very interested. Can you tell me how to generate  the sequences.hkl?? Thanks!

**Comment by minxueric** [comment]
Thank you for you interest in our work.  As is commented in the source code, the genome is a self-maintained UCSC hg19 genome hickle file, one can download chr[1-22,X,Y].fa.gz on http://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/. I just read these sequences into a dictionary variable and saved it in a hickle file.

**Comment by guoyanb** [comment]
Can you share your the 'sequences.hkl' data or code ?

**Comment by guoyanb** [comment]
![2018-10-31 16-28-40](https://user-images.githubusercontent.com/39645139/47775234-0f4efd80-dd2a-11e8-953c-2e4321cedad1.png)
Hello, is the data form is the same as your hkl? In addition, is the 'SNEDE0000EMT' of your codes different from the 'ENCSR000EMT' of Table 1 in the paper ? Thanks!

**Comment by minxueric** [comment]
Sorry for replying late. I have checked my 'sequences.hkl', and data looks like 
{'chr1': 'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...',
'chr2':
...
}
The keys are 'chr1' to 'chrY', and the corresponding values are the ACGT strings.
I have uploaded this file to allow you use this directly.

**Comment by minxueric** [comment]
For your second question, they are the same.

**Comment by guoyanb** [comment]
Ok, thanks!
 In addition, I have a question ,If you can explain it to me, I will be very grateful.
Do they have differences between the 'SNEDE0000EMT' of the first picture  and the 'ENCSR000EMT' of the second picture, and In other words, what is the relation between them?  
 
![1](https://user-images.githubusercontent.com/39645139/48037536-ad6a1a00-e1a7-11e8-9fdb-592651972877.png)
![2](https://user-images.githubusercontent.com/39645139/48037537-ad6a1a00-e1a7-11e8-9896-8f09cc9a8ef0.png)

**Comment by minxueric** [comment]
Actually, the 'SNEDE0000EMT' is the code used in our own local dataset, and the correct code should be 'ENCS000EMT' which can be found at encodeproject.org.

**Comment by guoyanb** [comment]
Thank you ! In other words, the datasets which were the preprocessed  data in the folder ‘spot’ is all the 6 cell type dataset，Right?
Excuse me, can I do some agorithm researches based on the data in the 'spot'?

**Comment by Mxc666** [comment]
您好，您上传的'sequences.hkl'版本过老，在python 3上跑不了。所以想请教下您我自己如何可以生成这个序列文件，感激不尽
